version: '3'
services: 
  mongo:
    image: 'mongo:4.4.1'
    restart: always
    container_name: 'rest-api-mongo'
    environment:
      - MONGO_INITDB_ROOT_USERNAME=silemi5
      - MONGO_INITDB_ROOT_PASSWORD=ocisly
      - MONGO_INITDB_DATABASE=rest-api-db
    volumes:
      - ./mongo-volume:/data/db
      - ./docker-entrypoint-initdb:/docker-entrypoint-initdb.d:ro
    ports: 
      - '27017-27019:27017-27019'
  
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment: 
      - ME_CONFIG_MONGODB_ADMINUSERNAME=silemi5
      - ME_CONFIG_MONGODB_ADMINPASSWORD=ocisly
